(() => {
  const es = document.documentElement.lang.toLowerCase().startsWith('es');
  const t = (spanish, english) => es ? spanish : english;
  const style = document.createElement('style');
  style.textContent = `
    .dfl-chat-launcher{position:fixed;right:24px;bottom:24px;width:58px;height:58px;border:0;border-radius:50%;background:var(--primary,#0093c9);color:#fff;font-size:1.45rem;cursor:pointer;box-shadow:0 12px 30px #0004;z-index:3500}
    .dfl-chat-panel{position:fixed;right:24px;bottom:94px;width:min(390px,calc(100vw - 32px));height:min(610px,calc(100vh - 120px));display:none;flex-direction:column;overflow:hidden;border:1px solid #d9e1e6;border-radius:18px;background:#fff;box-shadow:0 18px 55px #0004;z-index:3499}.dfl-chat-panel.open{display:flex}
    .dfl-chat-head{padding:1rem;background:#111;color:#fff;display:flex;align-items:center;gap:.75rem}.dfl-chat-head-copy{flex:1}.dfl-chat-head-copy strong,.dfl-chat-head-copy span{display:block}.dfl-chat-head-copy span{color:#cdd4d8;font-size:.78rem}.dfl-chat-close{border:0;background:transparent;color:#fff;font-size:1.35rem;cursor:pointer}.dfl-chat-status{width:10px;height:10px;border-radius:50%;background:#35c759}
    .dfl-chat-mode{padding:.45rem .8rem;background:#eef8fc;color:#16637c;font-size:.74rem;text-align:center}.dfl-chat-messages{flex:1;overflow-y:auto;padding:1rem;background:#f5f7f8}.dfl-chat-row{display:flex;margin-bottom:.75rem}.dfl-chat-row.user{justify-content:flex-end}.dfl-chat-bubble{max-width:84%;padding:.7rem .85rem;border-radius:14px 14px 14px 4px;background:#fff;color:#222;line-height:1.42;box-shadow:0 2px 8px #0001}.dfl-chat-row.user .dfl-chat-bubble{border-radius:14px 14px 4px 14px;background:var(--primary,#0093c9);color:#fff}
    .dfl-chat-options{display:flex;flex-wrap:wrap;gap:.5rem;margin:.25rem 0 .85rem}.dfl-chat-option{border:1px solid var(--primary,#0093c9);border-radius:999px;padding:.5rem .72rem;background:#fff;color:#08759d;cursor:pointer;font:inherit;font-size:.85rem}.dfl-chat-form{display:flex;gap:.5rem;padding:.75rem;border-top:1px solid #e4e8ea}.dfl-chat-input{flex:1;min-width:0;padding:.7rem .8rem;border:1px solid #ccd5da;border-radius:12px;font:inherit}.dfl-chat-send{border:0;border-radius:12px;padding:0 .9rem;background:var(--primary,#0093c9);color:#fff;font-weight:700;cursor:pointer}
    @media(max-width:520px){.dfl-chat-launcher{right:16px;bottom:16px}.dfl-chat-panel{right:16px;bottom:86px;height:min(620px,calc(100vh - 105px))}}
  `;
  document.head.appendChild(style);

  document.body.insertAdjacentHTML('beforeend', `
    <button class="dfl-chat-launcher" type="button" aria-label="${t('Abrir asistente','Open assistant')}" aria-expanded="false">&#128172;</button>
    <aside class="dfl-chat-panel" aria-label="Deep Finance Lab assistant" aria-hidden="true">
      <div class="dfl-chat-head"><span class="dfl-chat-status"></span><div class="dfl-chat-head-copy"><strong>${t('Asistente Deep Finance','Deep Finance Assistant')}</strong><span>${t('Citas y consultas','Appointments and enquiries')}</span></div><button class="dfl-chat-close" type="button" aria-label="${t('Cerrar chat','Close chat')}">&times;</button></div>
      <div class="dfl-chat-mode">${t('Asistente conectado','Assistant connected')}</div><div class="dfl-chat-messages" aria-live="polite"></div>
      <form class="dfl-chat-form"><input class="dfl-chat-input" autocomplete="off" placeholder="${t('Escribe tu mensaje...','Type your message...')}" aria-label="${t('Mensaje','Message')}"><button class="dfl-chat-send">${t('Enviar','Send')}</button></form>
    </aside>`);

  const launcher=document.querySelector('.dfl-chat-launcher'), panel=document.querySelector('.dfl-chat-panel'), close=document.querySelector('.dfl-chat-close'), mode=document.querySelector('.dfl-chat-mode'), messages=document.querySelector('.dfl-chat-messages'), form=document.querySelector('.dfl-chat-form'), input=document.querySelector('.dfl-chat-input');
  let started=false, flow='menu'; const booking={};
  const services={
    [t('Finanzas estratégicas','Strategic Finance')]:{api:'Strategic Finance',people:['Professional 1','Professional 2']},
    [t('Analítica cuantitativa','Quantitative Analytics')]:{api:'Quantitative Analytics',people:['Professional 1','Professional 3']},
    [t('Asesoría en IA','AI Advisory')]:{api:'AI Advisory',people:['Professional 2','Professional 4']}
  };
  const api=async payload=>{const r=await fetch('/.netlify/functions/chatbot',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(payload)});const d=await r.json();if(!r.ok)throw new Error(d.error||'REQUEST_FAILED');return d};
  const slot=iso=>new Intl.DateTimeFormat(es?'es-CL':'en-US',{timeZone:'America/Santiago',weekday:'short',day:'numeric',month:'short',hour:'2-digit',minute:'2-digit'}).format(new Date(iso));
  function say(text,who='bot'){const row=document.createElement('div');row.className=`dfl-chat-row ${who}`;const bubble=document.createElement('div');bubble.className='dfl-chat-bubble';bubble.textContent=text;row.appendChild(bubble);messages.appendChild(row);messages.scrollTop=messages.scrollHeight}
  function options(items,handler,map=x=>x){const box=document.createElement('div');box.className='dfl-chat-options';items.forEach(label=>{const b=document.createElement('button');b.type='button';b.className='dfl-chat-option';b.textContent=label;b.onclick=()=>{box.remove();say(label,'user');handler(map(label))};box.appendChild(b)});messages.appendChild(box);messages.scrollTop=messages.scrollHeight}
  function menu(){flow='menu';say(t('¿Cómo puedo ayudarte?','How can I help you today?'));const book=t('Reservar una reunión','Book a meeting'),cancel=t('Cancelar una reserva','Cancel a booking'),mine=t('Ver mis reservas','View my bookings');options([book,mine,cancel,t('Hacer una consulta','Ask a question')],choice=>{if(choice===book){flow='service';say(t('Elige el tipo de reunión:','Choose the type of meeting:'));options(Object.keys(services),selectService)}else if(choice===mine){flow='lookup-identity';say(t('Escribe el correo o teléfono usado al reservar.','Type the email or phone used for the booking.'))}else if(choice===cancel){flow='cancel-professional';say(t('Selecciona el profesional asociado:','Select the associated professional:'));options(['Professional 1','Professional 2','Professional 3','Professional 4'],p=>{booking.cancelProfessional=p;flow='cancel-code';say(t('Escribe la referencia incluida en la confirmación.','Type the reference included in the confirmation.'))})}else{flow='question';say(t('Cuéntame qué deseas saber sobre nuestros servicios financieros y de IA.','Tell me what you would like to know about our financial and AI services.'))}})}
  function selectService(label){booking.service=services[label].api;booking.serviceLabel=label;flow='professional';say(t('Selecciona un profesional:','Select a professional:'));options(services[label].people,selectProfessional)}
  async function selectProfessional(professional){booking.professional=professional;flow='slot';say(t(`Consultando disponibilidad de ${professional}...`,`Checking ${professional}'s availability...`));try{const result=await api({action:'availability',professional,timeMin:new Date().toISOString(),timeMax:new Date(Date.now()+21*86400000).toISOString()});if(!result.slots.length){say(t('No encontramos horas disponibles durante las próximas tres semanas.','No available times were found during the next three weeks.'));return menu()}const labels=result.slots.map(slot),map=Object.fromEntries(labels.map((x,i)=>[x,result.slots[i]]));say(t('Horas disponibles:','Available times:'));options(labels,x=>{booking.slot=x;flow='name';say(t('Escribe tu nombre completo.','Type your full name.'))},x=>map[x])}catch{say(t('El calendario no está disponible en este momento.','The calendar is temporarily unavailable.'));menu()}}
  async function confirmBooking(choice){if(choice!==t('Confirmar reserva','Confirm booking'))return menu();say(t('Procesando la reserva...','Processing the booking...'));try{const r=await api({action:'book',service:booking.service,professional:booking.professional,start:booking.slot,name:booking.name,email:booking.email,phone:booking.phone,locale:es?'es':'en'});say(t(`${r.demo?'Reserva de demostración creada':'Cita confirmada'}. Referencia: ${r.reference}.`,`${r.demo?'Demo booking created':'Appointment confirmed'}. Reference: ${r.reference}.`))}catch(e){say(e.message==='SLOT_UNAVAILABLE'?t('Esa hora acaba de ser ocupada.','That time was just taken.'):t('No se pudo completar la reserva.','The booking could not be completed.'))}menu()}
  async function confirmCancel(choice){if(choice!==t('Confirmar cancelación','Confirm cancellation'))return menu();say(t('Procesando la cancelación...','Processing the cancellation...'));try{const identity=booking.cancelIdentity.includes('@')?{email:booking.cancelIdentity}:{phone:booking.cancelIdentity};const r=await api({action:'cancel',professional:booking.cancelProfessional,reference:booking.cancelReference,...identity});say(t(`${r.demo?'Cancelación de demostración completada':'Cita cancelada'}. Referencia: ${r.reference}.`,`${r.demo?'Demo cancellation completed':'Appointment cancelled'}. Reference: ${r.reference}.`))}catch(e){say(e.message==='IDENTITY_MISMATCH'?t('El correo o teléfono no coincide con la reserva.','The email or phone does not match the booking.'):e.message==='BOOKING_NOT_FOUND'?t('No encontramos una reserva con esa referencia.','No booking was found with that reference.'):t('No se pudo completar la cancelación.','The cancellation could not be completed.'))}menu()}
  async function text(value){if(flow==='name'){booking.name=value;flow='email';say(t('Escribe el correo que recibirá la confirmación.','Type the email that should receive the confirmation.'))}else if(flow==='email'){if(!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(value))return say(t('Ingresa un correo válido.','Enter a valid email address.'));booking.email=value;flow='phone';say(t('Escribe el número de WhatsApp en formato internacional, o escribe Omitir.','Type the WhatsApp number in international format, or type Skip.'))}else if(flow==='phone'){const skip=t('omitir','skip');if(value.toLowerCase()!==skip&&!/^\+[1-9]\d{7,14}$/.test(value.replace(/\s/g,'')))return say(t('Usa formato internacional comenzando con +, o escribe Omitir.','Use international format beginning with +, or type Skip.'));booking.phone=value.toLowerCase()===skip?'':value.replace(/\s/g,'');flow='confirm-booking';say(t(`Confirma: ${booking.serviceLabel}, ${booking.professional}, ${slot(booking.slot)}, para ${booking.name}.`,`Confirm: ${booking.serviceLabel}, ${booking.professional}, ${slot(booking.slot)}, for ${booking.name}.`));options([t('Confirmar reserva','Confirm booking'),t('Comenzar de nuevo','Start over')],confirmBooking)}else if(flow==='lookup-identity'){const identity=value.includes('@')?{email:value}:{phone:value.replace(/\s/g,'')};say(t('Buscando tus reservas...','Looking up your bookings...'));try{const r=await api({action:'bookings',...identity});say(r.bookings.length?r.bookings.map(x=>`${slot(x.start)} — ${x.professional} — ${x.reference}`).join('\n'):t('No encontramos reservas activas con esos datos.','No active bookings were found for those details.'))}catch{say(t('No se pudieron consultar las reservas.','Bookings could not be retrieved.'))}menu()}else if(flow==='cancel-code'){const ref=value.trim().toUpperCase();if(!/^DFL-[A-F0-9]{32}$/.test(ref))return say(t('Ingresa la referencia completa de la confirmación.','Enter the complete reference from the confirmation.'));booking.cancelReference=ref;flow='cancel-identity';say(t('Escribe el correo o teléfono usado al reservar.','Type the email or phone used for the booking.'))}else if(flow==='cancel-identity'){booking.cancelIdentity=value.trim();flow='confirm-cancel';say(t(`¿Deseas cancelar ${booking.cancelReference}?`,`Do you want to cancel ${booking.cancelReference}?`));options([t('Confirmar cancelación','Confirm cancellation'),t('Mantener reserva','Keep booking')],confirmCancel)}else if(flow==='question'){say(t('Pensando...','Thinking...'));try{say((await api({action:'ask',question:value})).text)}catch{say(t('No pude responder ahora. Inténtalo nuevamente.','I could not answer right now. Please try again.'))}menu()}else{say(t('Elige una de las opciones disponibles.','Choose one of the available options.'));menu()}}
  async function open(){panel.classList.add('open');panel.setAttribute('aria-hidden','false');launcher.setAttribute('aria-expanded','true');if(!started){started=true;try{const cfg=await api({action:'bootstrap'});if(!cfg.demo)mode.remove();say(t(`¡Hola! Soy el asistente de Deep Finance Lab. ${cfg.demo?'El sistema está en modo demostración.':'Puedo gestionar citas en cuatro calendarios profesionales.'}`,`Hello! I am the Deep Finance Lab assistant. ${cfg.demo?'The scheduling system is in demo mode.':'I can manage appointments across four professional calendars.'}`))}catch{say(t('¡Hola! El servicio de reservas no está disponible temporalmente.','Hello! The scheduling service is temporarily unavailable.'))}menu()}input.focus()}
  function shut(){panel.classList.remove('open');panel.setAttribute('aria-hidden','true');launcher.setAttribute('aria-expanded','false')}
  launcher.onclick=()=>panel.classList.contains('open')?shut():open(); close.onclick=shut; document.addEventListener('keydown',e=>{if(e.key==='Escape')shut()}); form.onsubmit=e=>{e.preventDefault();const value=input.value.trim();if(!value)return;input.value='';say(value,'user');text(value)};
})();
